cifar-10-lt-ir100:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4
  model_name: resnet32
  model_layers: 30
  # 预训练模型路径
  pretrained_model_path: /nfs/xwx/model-doctor-xwx/output/model/pretrained/resnet32-cifar-10-lt-ir100-refl-th-0.4-wr/checkpoint.pth
  kernel_dict_path: /nfs/xwx/model-doctor-xwx/modify_kernel/kernel_dict

cifar-10-lt-ir10:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4
  model_name: resnet32
  model_layers: 30
  # 预训练模型路径
  pretrained_model_path: /nfs/xwx/model-doctor-xwx/output/model/pretrained/resnet32/cifar-10-lt-ir10/lr0.1/custom_lr_scheduler/ce_loss/2022-07-01_00-25-40/best-model-acc0.8749.pth
  kernel_dict_path: /nfs/xwx/model-doctor-xwx/modify_kernel/kernel_dict


