cifar-10:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

cifar-10-lt-ir10:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 2e-4

cifar-10-lt-ir100:
  model:
    in_channels: 3
    num_classes: 10
  optimizer:
    momentum: 0.9
    weight_decay: 2e-4
  sample_per_class_path: /nfs/xwx/model-doctor-xwx/configs/sample_per_class/cifar-10-lt-ir100.npy
    
cifar-100:
  model:
    in_channels: 3
    num_classes: 100
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

cifar-100-lt-ir10:
  model:
    in_channels: 3
    num_classes: 100
  optimizer:
    momentum: 0.9
    weight_decay: 1e-3

cifar-100-lt-ir50:
  model:
    in_channels: 3
    num_classes: 100
  optimizer:
    momentum: 0.9
    weight_decay: 1e-3

cifar-100-lt-ir100:
  model:
    in_channels: 3
    num_classes: 100
  optimizer:
    momentum: 0.9
    weight_decay: 1e-3

imagenet-lt:
  model:
    in_channels: 3
    num_classes: 1000
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4

inaturalist2018:
  model:
    in_channels: 3
    num_classes: 8142
  optimizer:
    momentum: 0.9
    weight_decay: 5e-4
